INSERT INTO parametros_legales (par_id, nombre, valor)
VALUES
(1,'SALARIO MINIMO', 908526.0),
(2,'AUXILIO DE TRANSPORTE', 106454.0),
(3,'PORCENTAJE DE SALUD POR EMPLEADO', 0.04),
(4,'PORCENTAJE DE PENSION POR EMPLEADO', 0.04),
(5,'VALOR HORA EXTRA DIURNA ORDINARIA', 1.25),
(6,'VALOR HORA EXTRA NOCTURNA ORDINARIA', 1.75),
(7,'VALOR HORA EXTRA DIURNA DOMINICAL O FESTIVO', 2),
(8,'VALOR HORA EXTRA NOCTURNA DOMINICAL O FESTIVO', 2.5),
(9,'VALOR RECARGO NOCTURNO', 0.35),
(10,'VALOR RECARGO DIURNO DOMINICAL O FESTIVO', 0.75),
(11,'VALOR RECARGO NOCTURNO DOMINICAL O FESTIVO', 1.10);