server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://microservicios-mysql8:3306/bd_hojas_vida?serverTimezone=America/Bogota&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: sasa2121
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect 
    hibernate: 
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8099/eureka/